

name: Cloud Windows PC
on: workflow_dispatch

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "MyPass123!" -Force)
        shell: powershell

      - name: Install Rust and Bore
        run: |
          Invoke-WebRequest -Uri "https://win.rustup.rs/x86_64" -OutFile rustup-init.exe
          .\rustup-init.exe -y
          $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"
          cargo install bore-cli
        shell: powershell

      - name: Tunnel RDP with Bore
        run: |
          $env:PATH = "$env:USERPROFILE\.cargo\bin;$env:PATH"
          bore local 3389 --to bore.pub
        shell: powershell

      - name: Keep Alive
        run: Start-Sleep -Seconds 21000
        shell: powershell

